### ISSUE TITLE
loading inhibitor arcs from pnml

### ISSUE THREAD

**Issue by vanrein** [fpom/snakes#12]
I am trying to load a PNML file with inhibitor arcs, but they don't seem to arrive; minimal tests with `snakes.pnml.loads()` followed by `snakes.pnml.dumps()` drop any reference to inhibition.  Is this missing in the implementation?

FWIW, I tried [TAPAAL](http://www.tapaal.net) notation,
```
  <arc id="place37:trans25" source="place37" target="trans25" type="tapnInhibitor">
   <inscription>
      ...
   </inscription>
  </arc>
```
and
```
  <arc id="place37:trans25" source="place37" target="trans25" type="inhibitor">
   <inscription>
      ...
   </inscription>
  </arc>
```
as well as the [version by Weber et al](http://xml.coverpages.org/WeberPNML200204.pdf),
```
  <arc id="place47:trans24" source="place47" target="trans24">
   <inscription>
      ...
   </inscription>
   <type value="inhibitor"/>
  </arc>
```
but all these inhibitor notations got stripped.

I also looked through the `snakes.pnml` module for the word `inhibitor` and did not find it.

Is this difficult to add?  It seems useful?

**Comment by fpom** [comment]
SNAKES is only partially compliant with PNML, for inhibitor arcs, it encloses the whole arc within and `<inhibitor>...</inhibitor>` tag.

Note 1: you'll find how each object is serialised into PNML in the `__pnml__` method of the corresponding class.

Note 2: there is no chance that SNAKES can be fully PNML compliant because it has much more features than PNML. So I've implemented only a basic support that is OK with P/T nets without extensions. However, any SNAKES nets can be saved to/loaded from a PNML file that will respect the standard if the net is a P/T net without extensions.

**Comment by vanrein** [comment]
Thanks for your response.  I am trying to get an [event-based scheduler](https://github.com/vanrein/perpetuum) derived from Petri net sync, so the ideas of model checking can be used to take some of the burden out of, specifically, the complexity and dynamicity of [key management processes](http://internetwide.org/blog/2016/12/20/idhub-2-middleware.html).

In spite of the existence of a PNML standard and our modest requirements (P/T with inhibitor arcs), I find that many tools don't connect up all over the place.  This is caused by the variations in research directions, of course, but I had hoped SNAKES was an exception.

F'gimme for not investing in your project by adding this to SNAKES.  There are so many connections that don't line up that I suppose I'll do what everyone does... and build dedicated tooling.  With some dismay, because I like to think of open source software as a chance to avoid the not-invented-here syndrome.

**Comment by fpom** [comment]
I completely agree with your point of view. Unfortunately, PNML is fine as long a your stick with P/T nets. Then it may become a nightmare because it's a very complex standard. This explains why so many tools have limited (like SNAKES) or buggy support of PNML.

If you send me a clear specification of what you need (what do you read/write, in which format precisely) probably there's a simple solution to have it implemented in SNAKES as a plugin. Please send me an email to discuss this further.

**Comment by vanrein** [comment]
Great offer, thanks.

But I'm suspecting there might be more problems of this kind lurking; I already ran into various notations for inhibitor arcs; so I concluded from your 1st response that it is better (albeit a bit disappointing from a code sharing view point) to tackle PNML from a more syntactical approach.  It's not such a big step anyway --as I want to [compile Petri nets to code](https://github.com/vanrein/perpetuum)-- and it will make it easier for me to accommodate other tools' input.

So, I won't continue on this path with SNAKES.  Thanks for helping me understand that PNML is not as ideal as specs can be `;-)`

**Comment by fpom** [comment]
As soon as you have managed to implement the subset of PNML that you need, it will be OK as long as you stick with the same set of tools. The next problem will be the semantics: PNML allows to exchange syntactically, but on many aspects the semantics is varying from one tool to another.
