### ISSUE TITLE
Patch for /snakes/nets.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fpom/snakes#3]
```
Added __eq__() and __getitem__ to nets.Place
```

Original issue reported on code.google.com by `erwinka...@gmail.com` on 12 Feb 2015 at 9:41

Attachments:
- [nets.py.patch](https://storage.googleapis.com/google-code-attachments/python-snakes/issue-3/comment-0/nets.py.patch)

**Comment by fpom** [comment]
Thank you for this patch but it could not work at all programmed this way (there is no `value` attribute in places and your `__getitem__` calls itself in a endless recursion). Moreover, I'll not add this two methods:
- `__eq__` is not implemented because its semantics is not clear, should it be same name, same tokens, both? Fortunately, one may use `p1.name == p2.name` or `p1.tokens == p2.tokens`
- what `__getitem__` should do is not clear neither, there are methods and the `tokens` attribute to query a place's content
