### ISSUE TITLE
PetriNet.set_marking empty the net marking after a place rename

### ISSUE THREAD

**Issue by albreche** [fpom/snakes#6]
Here is the scenario (python 2.7.6, ubuntu 14.04 LTS): 

n = PetriNet('N')
n.add_place(Place('p'))
n.set_marking(Marking({'p': MultiSet([1])}))
n.get_marking()

> Marking({'p': MultiSet([1])})  #OK

n.place('p').rename('p1')
n.get_marking()

> Marking({'p': MultiSet([1])}) 

here; places in marking are not renamed (maybe a design choice?). But the problem is later : 

n.set_marking(Marking({'p1': MultiSet([1])}))
n.get_marking()

> Marking({}) # KO

But, p1 is a place of n , hence the marking of net should be Marking({'p1': MultiSet([1])}) 
n.place()

> [Place('p1', MultiSet([]), tAll)]

**Comment by fpom** [comment]
Thanks for this report, this was actually a bug that has been fixed in commit f368e32732042fbaa95574b26b21d97d75e006cf (just pushed). The renaming of the place was not propagated to the net.

Note that `set_marking` however had the correct behaviour: it is designed so that it ignores places that are not part of the net and clears those not in the given marking. So, here, `p1` was considered to be not present in the net because of the bug, and `p` was cleared because it was not in the marking passed to the method.

**Comment by albreche** [comment]
it's ok , tnx
